[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/ffmpeg/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Resource-Policy = "cross-origin"
